# Data Cleaning and Peperation for PostgreSQL Import

In order to prepare our datasets for import to our PostgreSQL database, we need to ensure the data is clean, structured correctly, and compatible with PostgreSQL's requirements. This comprehensive data cleaning process aims to achieve data integrity, consistency, and compatibility, which are crucial for efficient data handling and analysis in PostgreSQL.

## Project Overview:
To achieve our goals, we will follow a structured data-cleaning process detailed in the steps below, and work from there to address any issues that arise:

1. **Load Data:** Import the dataset into the notebook to begin cleaning.
2. **Initial Inspection:** Perform an initial inspection to understand the structure and content of the data.
3. **Check Data Types:** Ensure each column has the appropriate data type matching PostgreSQL's data types.
4. **Identify Problematic Entries:** Identify any entries that may cause issues in analysis or importing.
5. **Replace Invalid Entries:** Correct or remove any invalid entries identified in the previous step.
6. **Detect and Handle Duplicates:** Identify and handle duplicate records in the dataset.
7. **Detect and Handle Missing Values:** Address missing values appropriately based on the context.
8. **Detect and Handle Outliers:** Identify and manage outliers that could skew analysis.
9. **Data Consistency:** Ensure consistency in data entries, such as standardizing units or formats.
10. **Final Cleaning:** Perform any final cleaning steps to ensure the dataset is ready.
11. **Log Issues:** Log any issues encountered during the cleaning process for future reference.
12. **Save Cleaned Data:** Save the cleaned dataset to a file.
13. **Processing and Saving Cleaned CSV Files:** Process and save the cleaned data into CSV files ready for import.


## Key Requirements for Data Cleaning:
### Data Integrity and Consistency:
- Ensure all data is accurate, complete, and consistent. This includes checking for missing values, outliers, and correcting any erroneous or inconsistent data entries.

### Data Types:
- Ensure that each column in your dataset has an appropriate data type that matches PostgreSQL's data types. Common types include integer, numeric, text, date, timestamp, etc. Make sure dates and timestamps are formatted correctly.

### Null Values:
- Handle null values appropriately. Decide whether to fill in missing values, discard rows with nulls (if applicable), or set default values. PostgreSQL handles nulls differently from some other databases, so ensure your approach aligns with PostgreSQL's handling of nulls.

### Data Cleaning Tools and Techniques:
- Use appropriate tools and techniques to clean and transform the data as per PostgreSQL's requirements.

### File Format and Size:
- Ensure your dataset is in a compatible file format for import into PostgreSQL, such as CSV, JSON, or SQL dump files. Pay attention to file size limitations and consider breaking large datasets into manageable chunks if needed.

### Import Method:
- Choose the appropriate method for importing data into PostgreSQL, such as using the COPY command, pg_restore for SQL dumps, or tools like psql or pgAdmin for interactive imports. Each method may have specific requirements and optimizations.

## Step 1: Load Data

In [10]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

# Define the base path to the CSV files
base_path = 'C:/Users/matth/ecommerce_mba_project/data/raw'
cleaned_path = 'C:/Users/matth/ecommerce_mba_project/data/cleaned'
log_path = 'C:/Users/matth/ecommerce_mba_project/data/logs'

# Ensure the cleaned path and log path exist
os.makedirs(cleaned_path, exist_ok=True)
os.makedirs(log_path, exist_ok=True)

# Define the paths to the CSV files
csv_files = {
    'sale_report': os.path.join(base_path, 'Sale Report.csv'),
    'p_and_l_march_2021': os.path.join(base_path, 'P  L March 2021.csv'),
    'amazon_sale_report': os.path.join(base_path, 'Amazon Sale Report.csv'),
    'may_2022': os.path.join(base_path, 'May-2022.csv')
}

# Load CSV files into DataFrames
sale_report_df = pd.read_csv(csv_files['sale_report'])
p_and_l_march_2021_df = pd.read_csv(csv_files['p_and_l_march_2021'])
amazon_sale_report_df = pd.read_csv(csv_files['amazon_sale_report'], low_memory=False)
may_2022_df = pd.read_csv(csv_files['may_2022'])

# Display initial rows
print("Sale Report DataFrame:")
print(sale_report_df.head())

print("\nP & L March 2021 DataFrame:")
print(p_and_l_march_2021_df.head())

print("\nAmazon Sale Report DataFrame:")
print(amazon_sale_report_df.head())

print("\nMay 2022 DataFrame:")
print(may_2022_df.head())

Sale Report DataFrame:
   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

P & L March 2021 DataFrame:
   index             Sku    Style Id  Catalog Category Weight TP 1    TP 2  \
0      0    Os206_3141_S  Os206_3141  Moments    Kurta    0.3  538  435.78
1      1    Os206_3141_M  Os206_3141  Moments    Kurta    0.3  538  435.78
2      2    Os206_3141_L  Os206_3141  Moments    Kurta    0.3  538  435.78
3      3   Os206_3141_XL  Os206_3141  Moments    Kurta    0.3  538  435.78
4      4  Os206_3141_2XL  Os206_3141  Moments    Kurta    0.3  538  435.78

  MRP Old Final MRP Old Ajio MRP Amazon MRP Amazon FBA MRP Flipkart MRP  \
0    2178          2295     2295       2295           2295         2295
1    2178          2295     2295       2295           2295         2295
2    2178          2295     2295       2295           2295         2295
3    2178          2295     2295       2295           2295         2295
4    2178          2295     2295       2295           2295         2295

  Limeroad MRP Myntra MRP Paytm MRP Snapdeal MRP
0         2295       2295      2295         2295
1         2295       2295      2295         2295
2         2295       2295      2295         2295
3         2295       2295      2295         2295
4         2295       2295      2295         2295

Amazon Sale Report DataFrame:
   index             Order ID      Date                        Status  \
0      0  405-8078784-5731545  04-30-22                     Cancelled
1      1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2      2  404-0687676-7273146  04-30-22                       Shipped
3      3  403-9615377-8133951  04-30-22                     Cancelled
4      4  407-1069790-7240320  04-30-22                       Shipped

  Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0   Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1   Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2     Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3   Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4     Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL

        Category  ... currency  Amount    ship-city   ship-state  \
0            Set  ...      INR  647.62       MUMBAI  MAHARASHTRA
1          kurta  ...      INR  406.00    BENGALURU    KARNATAKA
2          kurta  ...      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3  Western Dress  ...      INR  753.33   PUDUCHERRY   PUDUCHERRY
4            Top  ...      INR  574.00      CHENNAI   TAMIL NADU

  ship-postal-code  ship-country  \
0         400081.0            IN
1         560085.0            IN
2         410210.0            IN
3         605008.0            IN
4         600073.0            IN

                                       promotion-ids    B2B  fulfilled-by  \
0                                                NaN  False     Easy Ship
1  Amazon PLCC Free-Financing Universal Merchant ...  False     Easy Ship
2       IN Core Free Shipping 2015/04/08 23-48-5-108   True           NaN
3                                                NaN  False     Easy Ship
4                                                NaN  False           NaN

  Unnamed: 22
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 24 columns]

May 2022 DataFrame:
   index             Sku    Style Id  Catalog Category Weight   TP MRP Old  \
0      0    Os206_3141_S  Os206_3141  Moments    Kurta    0.3  538    2178
1      1    Os206_3141_M  Os206_3141  Moments    Kurta    0.3  538    2178
2      2    Os206_3141_L  Os206_3141  Moments    Kurta    0.3  538    2178
3      3   Os206_3141_XL  Os206_3141  Moments    Kurta    0.3  538    2178
4      4  Os206_3141_2XL  Os206_3141  Moments    Kurta    0.3  538    2178

  Final MRP Old Ajio MRP Amazon MRP Amazon FBA MRP Flipkart MRP Limeroad MRP  \
0          2295     2295       2295           2295         2295         2295
1          2295     2295       2295           2295         2295         2295
2          2295     2295       2295           2295         2295         2295
3          2295     2295       2295           2295         2295         2295
4          2295     2295       2295           2295         2295         2295

  Myntra MRP Paytm MRP Snapdeal MRP
0       2295      2295         2295
1       2295      2295         2295
2       2295      2295         2295
3       2295      2295         2295
4       2295      2295         2295

## Step 2: Initial Inspection

In [11]:
# Display summary statistics
print("Sale Report Summary:")
print(sale_report_df.describe(include='all'))

print("\nP & L March 2021 Summary:")
print(p_and_l_march_2021_df.describe(include='all'))

print("\nAmazon Sale Report Summary:")
print(amazon_sale_report_df.describe(include='all'))

print("\nMay 2022 Summary:")
print(may_2022_df.describe(include='all'))

Sale Report Summary:
              index SKU Code Design No.        Stock Category  Size Color
count   9271.000000     9188       9235  9235.000000     9226  9235  9226
unique          NaN     9170       1594          NaN       21    11    62
top             NaN    #REF!      J0096          NaN    KURTA     S  Blue
freq            NaN       15         10          NaN     3726  1353   782
mean    4635.000000      NaN        NaN    26.246454      NaN   NaN   NaN
std     2676.451507      NaN        NaN    58.462891      NaN   NaN   NaN
min        0.000000      NaN        NaN     0.000000      NaN   NaN   NaN
25%     2317.500000      NaN        NaN     3.000000      NaN   NaN   NaN
50%     4635.000000      NaN        NaN     8.000000      NaN   NaN   NaN
75%     6952.500000      NaN        NaN    31.000000      NaN   NaN   NaN
max     9270.000000      NaN        NaN  1234.000000      NaN   NaN   NaN

P & L March 2021 Summary:
              index           Sku Style Id Catalog Category Weight  TP 1  \
count   1330.000000          1330     1330    1330     1330   1330  1330
unique          NaN          1330      254       9        5      4    93
top             NaN  Os206_3141_S    Os160     Mix    Kurta    0.3   395
freq            NaN             1        8     830      820    820   139
mean     664.500000           NaN      NaN     NaN      NaN    NaN   NaN
std      384.082239           NaN      NaN     NaN      NaN    NaN   NaN
min        0.000000           NaN      NaN     NaN      NaN    NaN   NaN
25%      332.250000           NaN      NaN     NaN      NaN    NaN   NaN
50%      664.500000           NaN      NaN     NaN      NaN    NaN   NaN
75%      996.750000           NaN      NaN     NaN      NaN    NaN   NaN
max     1329.000000           NaN      NaN     NaN      NaN    NaN   NaN

          TP 2 MRP Old Final MRP Old Ajio MRP Amazon MRP Amazon FBA MRP  \
count     1330    1330          1330     1330       1330           1330
unique      93      67            53       52         53             53
top     319.95    1695          1895     1895       1895           1895
freq       139     156           172      173        203            203
mean       NaN     NaN           NaN      NaN        NaN            NaN
std        NaN     NaN           NaN      NaN        NaN            NaN
min        NaN     NaN           NaN      NaN        NaN            NaN
25%        NaN     NaN           NaN      NaN        NaN            NaN
50%        NaN     NaN           NaN      NaN        NaN            NaN
75%        NaN     NaN           NaN      NaN        NaN            NaN
max        NaN     NaN           NaN      NaN        NaN            NaN

       Flipkart MRP Limeroad MRP Myntra MRP Paytm MRP Snapdeal MRP
count          1330         1330       1330      1330         1330
unique           52           52         51        52           52
top            1895         1895       1895      1895         1695
freq            178          137        173       187          159
mean            NaN          NaN        NaN       NaN          NaN
std             NaN          NaN        NaN       NaN          NaN
min             NaN          NaN        NaN       NaN          NaN
25%             NaN          NaN        NaN       NaN          NaN
50%             NaN          NaN        NaN       NaN          NaN
75%             NaN          NaN        NaN       NaN          NaN
max             NaN          NaN        NaN       NaN          NaN

Amazon Sale Report Summary:
                index             Order ID      Date   Status Fulfilment  \
count   128975.000000               128975    128975   128975     128975
unique            NaN               120378        91       13          2
top               NaN  171-5057375-2831560  05-03-22  Shipped     Amazon
freq              NaN                   12      2085    77804      89698
mean     64487.000000                  NaN       NaN      NaN        NaN
std      37232.019822                  NaN       NaN      NaN        NaN
min          0.000000                  NaN       NaN      NaN        NaN
25%      32243.500000                  NaN       NaN      NaN        NaN
50%      64487.000000                  NaN       NaN      NaN        NaN
75%      96730.500000                  NaN       NaN      NaN        NaN
max     128974.000000                  NaN       NaN      NaN        NaN

       Sales Channel  ship-service-level    Style           SKU Category  ...  \
count          128975             128975   128975        128975   128975  ...
unique              2                  2     1377          7195        9  ...
top         Amazon.in          Expedited  JNE3797  JNE3797-KR-L      Set  ...
freq           128851              88615     4224           773    50284  ...
mean              NaN                NaN      NaN           NaN      NaN  ...
std               NaN                NaN      NaN           NaN      NaN  ...
min               NaN                NaN      NaN           NaN      NaN  ...
25%               NaN                NaN      NaN           NaN      NaN  ...
50%               NaN                NaN      NaN           NaN      NaN  ...
75%               NaN                NaN      NaN           NaN      NaN  ...
max               NaN                NaN      NaN           NaN      NaN  ...

       currency         Amount  ship-city   ship-state ship-postal-code  \
count    121180  121180.000000     128942       128942    128942.000000
unique        1            NaN       8955           69              NaN
top         INR            NaN  BENGALURU  MAHARASHTRA              NaN
freq     121180            NaN      11217        22260              NaN
mean        NaN     648.561465        NaN          NaN    463966.236509
std         NaN     281.211687        NaN          NaN    191476.764941
min         NaN       0.000000        NaN          NaN    110001.000000
25%         NaN     449.000000        NaN          NaN    382421.000000
50%         NaN     605.000000        NaN          NaN    500033.000000
75%         NaN     788.000000        NaN          NaN    600024.000000
max         NaN    5584.000000        NaN          NaN    989898.000000

        ship-country                                 promotion-ids     B2B  \
count         128942                                         79822  128975
unique             1                                          5787       2
top               IN  IN Core Free Shipping 2015/04/08 23-48-5-108   False
freq          128942                                         46100  128104
mean             NaN                                           NaN     NaN
std              NaN                                           NaN     NaN
min              NaN                                           NaN     NaN
25%              NaN                                           NaN     NaN
50%              NaN                                           NaN     NaN
75%              NaN                                           NaN     NaN
max              NaN                                           NaN     NaN

        fulfilled-by Unnamed: 22
count          39277       79925
unique             1           1
top        Easy Ship       False
freq           39277       79925
mean             NaN         NaN
std              NaN         NaN
min              NaN         NaN
25%              NaN         NaN
50%              NaN         NaN
75%              NaN         NaN
max              NaN         NaN

[11 rows x 24 columns]

May 2022 Summary:
              index           Sku Style Id Catalog Category Weight    TP  \
count   1330.000000          1330     1330    1330     1330   1330  1330
unique          NaN          1330      254       9        5      4    93
top             NaN  Os206_3141_S    Os160     Mix    Kurta    0.3   395
freq            NaN             1        8     830      820    820   139
mean     664.500000           NaN      NaN     NaN      NaN    NaN   NaN
std      384.082239           NaN      NaN     NaN      NaN    NaN   NaN
min        0.000000           NaN      NaN     NaN      NaN    NaN   NaN
25%      332.250000           NaN      NaN     NaN      NaN    NaN   NaN
50%      664.500000           NaN      NaN     NaN      NaN    NaN   NaN
75%      996.750000           NaN      NaN     NaN      NaN    NaN   NaN
max     1329.000000           NaN      NaN     NaN      NaN    NaN   NaN

       MRP Old Final MRP Old Ajio MRP Amazon MRP Amazon FBA MRP Flipkart MRP  \
count     1330          1330     1330       1330           1330         1330
unique      67            53       52         53             53           52
top       1695          1895     1895       1895           1895         1895
freq       156           172      173        203            203          178
mean       NaN           NaN      NaN        NaN            NaN          NaN
std        NaN           NaN      NaN        NaN            NaN          NaN
min        NaN           NaN      NaN        NaN            NaN          NaN
25%        NaN           NaN      NaN        NaN            NaN          NaN
50%        NaN           NaN      NaN        NaN            NaN          NaN
75%        NaN           NaN      NaN        NaN            NaN          NaN
max        NaN           NaN      NaN        NaN            NaN          NaN

       Limeroad MRP Myntra MRP Paytm MRP Snapdeal MRP
count          1330       1330      1330         1330
unique           52         51        52           52
top            1895       1895      1895         1695
freq            137        173       187          159
mean            NaN        NaN       NaN          NaN
std             NaN        NaN       NaN          NaN
min             NaN        NaN       NaN          NaN
25%             NaN        NaN       NaN          NaN
50%             NaN        NaN       NaN          NaN
75%             NaN        NaN       NaN          NaN
max             NaN        NaN       NaN          NaN

## Step 3: Identify Problematic Entries

To ensure data quality, we'll inspect the unique values in each column to identify any problematic entries. This step is crucial for understanding potential anomalies or outliers in the dataset, which could affect our analysis.

In [12]:
# Inspect unique values to identify problematic entries
def inspect_problematic_entries(df):
    for col in df.columns:
        unique_values = df[col].unique()
        print(f"\nUnique values in column '{col}':")
        print(unique_values[:10])  # Display first 10 unique values for inspection

inspect_problematic_entries(sale_report_df)
inspect_problematic_entries(p_and_l_march_2021_df)
inspect_problematic_entries(amazon_sale_report_df)
inspect_problematic_entries(may_2022_df)

Unique values in column 'index':
[0 1 2 3 4 5 6 7 8 9]

Unique values in column 'SKU Code':
['AN201-RED-L' 'AN201-RED-M' 'AN201-RED-S' 'AN201-RED-XL' 'AN201-RED-XXL'
 'AN202-ORANGE-L' 'AN202-ORANGE-M' 'AN202-ORANGE-S' 'AN202-ORANGE-XL'
 'AN202-ORANGE-XXL']

Unique values in column 'Design No.':
['AN201' 'AN202' 'AN203' 'AN204' 'AN205' 'AN206' 'AN207' 'AN209' 'AN210'
 'AN211']

Unique values in column 'Stock':
[ 5.  3.  6. 11. 16.  8. 14.  1.  2. 10.]

Unique values in column 'Category':
['AN : LEGGINGS' 'BLOUSE' 'PANT' 'BOTTOM' 'PALAZZO' 'SHARARA' 'SKIRT'
 'DRESS' 'KURTA SET' 'LEHENGA CHOLI']

Unique values in column 'Size':
['L' 'M' 'S' 'XL' 'XXL' 'FREE' 'XS' 'XXXL' '4XL' '5XL']

Unique values in column 'Color':
['Red' 'Orange' 'Maroon' 'Purple' 'Yellow' 'Green' 'Pink' 'Beige'
 'Navy Blue' 'Black']

Unique values in column 'index':
[0 1 2 3 4 5 6 7 8 9]

Unique values in column 'Sku':
['Os206_3141_S' 'Os206_3141_M' 'Os206_3141_L' 'Os206_3141_XL'
 'Os206_3141_2XL' 'Os206_3141_3XL' 'Os223_3142_S' 'Os223_3142_M'
 'Os223_3142_L' 'Os223_3142_XL']

Unique values in column 'Style Id':
['Os206_3141' 'Os223_3142' 'Os212_3143' 'Os214_3144' 'Os207_3145'
 'Os202_3146' 'Os181_5051' 'Os191_5052' 'Os197_5053' 'OS219_5054']

Unique values in column 'Catalog':
['Moments' 'Colors-8' 'Breeze-4' 'Rozana' 'Colors-7' 'Mix' 'Surmaya'
 'Four Gems 2' 'Nill']

Unique values in column 'Category':
['Kurta' 'Kurta Set' 'Gown' 'Tops' 'Nill']

Unique values in column 'Weight':
['0.3' '0.4' '0.2' 'Nill']

Unique values in column 'TP 1':
['538' '438' '505' '590' '381' '952' '570' '519' '714' '595']

Unique values in column 'TP 2':
['435.78' '354.78' '409.05' '477.90' '308.61' '771.12' '461.70' '420.39'
 '578.34' '481.95']

Unique values in column 'MRP Old':
['2178' '1778' '1895' '2038' '2378' '1538' '3858' '2298' '2098' '2878']

Unique values in column 'Final MRP Old':
['2295' '1895' '254' '2195' '2495' '1595' '3995' '2395' '2995' '1995']

Unique values in column 'Ajio MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Amazon MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Amazon FBA MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Flipkart MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Limeroad MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Myntra MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Paytm MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Snapdeal MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'index':
[0 1 2 3 4 5 6 7 8 9]

Unique values in column 'Order ID':
['405-8078784-5731545' '171-9198151-1101146' '404-0687676-7273146'
 '403-9615377-8133951' '407-1069790-7240320' '404-1490984-4578765'
 '408-5748499-6859555' '406-7807733-3785945' '407-5443024-5233168'
 '402-4393761-0311520']

Unique values in column 'Date':
['04-30-22' '04-29-22' '04-28-22' '04-27-22' '04-26-22' '04-25-22'
 '04-24-22' '04-23-22' '04-22-22' '04-21-22']

Unique values in column 'Status':
['Cancelled' 'Shipped - Delivered to Buyer' 'Shipped'
 'Shipped - Returned to Seller' 'Shipped - Rejected by Buyer'
 'Shipped - Lost in Transit' 'Shipped - Out for Delivery'
 'Shipped - Returning to Seller' 'Shipped - Picked Up' 'Pending']

Unique values in column 'Fulfilment':
['Merchant' 'Amazon']

Unique values in column 'Sales Channel ':
['Amazon.in' 'Non-Amazon']

Unique values in column 'ship-service-level':
['Standard' 'Expedited']

Unique values in column 'Style':
['SET389' 'JNE3781' 'JNE3371' 'J0341' 'JNE3671' 'SET264' 'J0095' 'JNE3405'
 'SET200' 'JNE3461']

Unique values in column 'SKU':
['SET389-KR-NP-S' 'JNE3781-KR-XXXL' 'JNE3371-KR-XL' 'J0341-DR-L'
 'JNE3671-TU-XXXL' 'SET264-KR-NP-XL' 'J0095-SET-L' 'JNE3405-KR-S'
 'SET200-KR-NP-A-XXXL' 'JNE3461-KR-XXL']

Unique values in column 'Category':
['Set' 'kurta' 'Western Dress' 'Top' 'Ethnic Dress' 'Bottom' 'Saree'
 'Blouse' 'Dupatta']

Unique values in column 'Size':
['S' '3XL' 'XL' 'L' 'XXL' 'XS' '6XL' 'M' '4XL' '5XL']

Unique values in column 'ASIN':
['B09KXVBD7Z' 'B09K3WFS32' 'B07WV4JV4D' 'B099NRCT7B' 'B098714BZP'
 'B08YN7XDSG' 'B08CMHNWBN' 'B081WX4G4Q' 'B08L91ZZXN' 'B08B3XF5MH']

Unique values in column 'Courier Status':
[nan 'Shipped' 'Cancelled' 'Unshipped']

Unique values in column 'Qty':
[ 0  1  2 15  3  9 13  5  4  8]

Unique values in column 'currency':
['INR' nan]

Unique values in column 'Amount':
[647.62 406.   329.   753.33 574.   824.   653.   399.      nan 363.  ]

Unique values in column 'ship-city':
['MUMBAI' 'BENGALURU' 'NAVI MUMBAI' 'PUDUCHERRY' 'CHENNAI' 'GHAZIABAD'
 'CHANDIGARH' 'HYDERABAD' 'Chennai' 'NOIDA']

Unique values in column 'ship-state':
['MAHARASHTRA' 'KARNATAKA' 'PUDUCHERRY' 'TAMIL NADU' 'UTTAR PRADESH'
 'CHANDIGARH' 'TELANGANA' 'ANDHRA PRADESH' 'RAJASTHAN' 'DELHI']

Unique values in column 'ship-postal-code':
[400081. 560085. 410210. 605008. 600073. 201102. 160036. 500032. 500008.
 600041.]

Unique values in column 'ship-country':
['IN' nan]

Unique values in column 'promotion-ids':
[nan
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-CXNSLNBROFDW4,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-WSJLDN3X7KEMO,Amazon PLCC Free-Financing Universal Merchant AAT-VL6FGQVGQVXUS,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-XVPICCHRWDCAI,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'IN Core Free Shipping 2015/04/08 23-48-5-108'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-WSJLDN3X7KEMO,Amazon PLCC Free-Financing Universal Merchant AAT-VL6FGQVGQVXUS,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-XVPICCHRWDCAI,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292']

Unique values in column 'B2B':
[False  True]

Unique values in column 'fulfilled-by':
['Easy Ship' nan]

Unique values in column 'Unnamed: 22':
[nan False]

Unique values in column 'index':
[0 1 2 3 4 5 6 7 8 9]

Unique values in column 'Sku':
['Os206_3141_S' 'Os206_3141_M' 'Os206_3141_L' 'Os206_3141_XL'
 'Os206_3141_2XL' 'Os206_3141_3XL' 'Os223_3142_S' 'Os223_3142_M'
 'Os223_3142_L' 'Os223_3142_XL']

Unique values in column 'Style Id':
['Os206_3141' 'Os223_3142' 'Os212_3143' 'Os214_3144' 'Os207_3145'
 'Os202_3146' 'Os181_5051' 'Os191_5052' 'Os197_5053' 'OS219_5054']

Unique values in column 'Catalog':
['Moments' 'Colors-8' 'Breeze-4' 'Rozana' 'Colors-7' 'Mix' 'Surmaya'
 'Four Gems 2' 'Nill']

Unique values in column 'Category':
['Kurta' 'Kurta Set' 'Gown' 'Tops' 'Nill']

Unique values in column 'Weight':
['0.3' '0.4' '0.2' 'Nill']

Unique values in column 'TP':
['538' '438' '505' '590' '381' '952' '570' '519' '714' '595']

Unique values in column 'MRP Old':
['2178' '1778' '1895' '2038' '2378' '1538' '3858' '2298' '2098' '2878']

Unique values in column 'Final MRP Old':
['2295' '1895' '254' '2195' '2495' '1595' '3995' '2395' '2995' '1995']

Unique values in column 'Ajio MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Amazon MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Amazon FBA MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Flipkart MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Limeroad MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Myntra MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Paytm MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

Unique values in column 'Snapdeal MRP':
['2295' '1895' '2195' '2495' '1595' '3995' '2395' '2995' '1995' '2795']

## Step 4: Replace Invalid Entries

From the inspection of unique values, we identified several problematic entries that need to be addressed including invalid entries such as 'Nill', 'nil', 'None', '', '#VALUE!', and 'NaN'. These entries can cause inaccuracies in data analysis if not handled properly.

To standardize the handling of missing or invalid entries, we replace them with NaN.

In [13]:
# Replace identified invalid entries with NaN
def replace_invalid_entries(df):
    df.replace(['Nill', 'nil', 'None', '', '#VALUE!', 'NaN'], np.nan, inplace=True)
    return df

sale_report_df = replace_invalid_entries(sale_report_df)
p_and_l_march_2021_df = replace_invalid_entries(p_and_l_march_2021_df)
amazon_sale_report_df = replace_invalid_entries(amazon_sale_report_df)
may_2022_df = replace_invalid_entries(may_2022_df)

# Check missing values
print("Sale Report Missing Values:")
print(sale_report_df.isnull().sum())

print("\nP & L March 2021 Missing Values:")
print(p_and_l_march_2021_df.isnull().sum())

print("\nAmazon Sale Report Missing Values:")
print(amazon_sale_report_df.isnull().sum())

print("\nMay 2022 Missing Values:")
print(may_2022_df.isnull().sum())

Sale Report Missing Values:
index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

P & L March 2021 Missing Values:
index              0
Sku                0
Style Id           0
Catalog           73
Category          73
Weight            73
TP 1               6
TP 2               6
MRP Old           37
Final MRP Old     37
Ajio MRP          37
Amazon MRP        37
Amazon FBA MRP    37
Flipkart MRP      37
Limeroad MRP      37
Myntra MRP        31
Paytm MRP         37
Snapdeal MRP      37
dtype: int64

Amazon Sale Report Missing Values:
index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

May 2022 Missing Values:
index              0
Sku                0
Style Id           0
Catalog           73
Category          73
Weight            73
TP                 6
MRP Old           37
Final MRP Old     37
Ajio MRP          37
Amazon MRP        37
Amazon FBA MRP    37
Flipkart MRP      37
Limeroad MRP      37
Myntra MRP        31
Paytm MRP         37
Snapdeal MRP      37
dtype: int64

## Step 5: Check for Duplicates

In [14]:
# Check for duplicates
def check_duplicates(df, df_name):
    duplicate_count = df.duplicated().sum()
    print(f"\nNumber of duplicate rows in {df_name}: {duplicate_count}")
    df.drop_duplicates(inplace=True)
    return df

sale_report_df = check_duplicates(sale_report_df, 'sale_report')
p_and_l_march_2021_df = check_duplicates(p_and_l_march_2021_df, 'p_and_l_march_2021')
amazon_sale_report_df = check_duplicates(amazon_sale_report_df, 'amazon_sale_report')
may_2022_df = check_duplicates(may_2022_df, 'may_2022')

Number of duplicate rows in sale_report: 0

Number of duplicate rows in p_and_l_march_2021: 0

Number of duplicate rows in amazon_sale_report: 0

Number of duplicate rows in may_2022: 0

## Step 6: Check Data Types

Here we'll ensure that column data types are correctly applied.

In [15]:
# Check current data types of the columns
def check_data_types(df, columns):
    for col in columns:
        print(f"Data type of column '{col}': {df[col].dtype}")

print("Sale Report Data Types:")
check_data_types(sale_report_df, ['Stock'])

print("\nP & L March 2021 Data Types:")
check_data_types(p_and_l_march_2021_df, ['Weight', 'TP 1', 'TP 2', 'MRP Old', 'Final MRP Old'])

print("\nAmazon Sale Report Data Types:")
check_data_types(amazon_sale_report_df, ['Amount'])

print("\nMay 2022 Data Types:")
check_data_types(may_2022_df, ['Weight', 'TP', 'MRP Old', 'Final MRP Old'])

Sale Report Data Types:
Data type of column 'Stock': float64

P & L March 2021 Data Types:
Data type of column 'Weight': object
Data type of column 'TP 1': object
Data type of column 'TP 2': object
Data type of column 'MRP Old': object
Data type of column 'Final MRP Old': object

Amazon Sale Report Data Types:
Data type of column 'Amount': float64

May 2022 Data Types:
Data type of column 'Weight': object
Data type of column 'TP': object
Data type of column 'MRP Old': object
Data type of column 'Final MRP Old': object

Several data type corrections are needed.

## Step 6: Convert Data Types

In [16]:
# Convert columns to appropriate data types
def convert_data_types(df, columns):
    for col in columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

sale_report_df = convert_data_types(sale_report_df, ['Stock'])
p_and_l_march_2021_df = convert_data_types(p_and_l_march_2021_df, ['Weight', 'TP 1', 'TP 2', 'MRP Old', 'Final MRP Old'])
amazon_sale_report_df = convert_data_types(amazon_sale_report_df, ['Amount'])
may_2022_df = convert_data_types(may_2022_df, ['Weight', 'TP', 'MRP Old', 'Final MRP Old'])

## Step 7: Handle Missing Values

Missing values in specified columns will be replaced with 0. This approach ensures that these columns do not contain NaN values, which could disrupt numerical analysis.

In [17]:
# Handle missing values
def handle_missing_values(df, columns):
    df.fillna({col: 0 for col in columns}, inplace=True)
    return df

sale_report_df = handle_missing_values(sale_report_df, ['Stock'])
p_and_l_march_2021_df = handle_missing_values(p_and_l_march_2021_df, ['Weight', 'TP 1', 'TP 2', 'MRP Old', 'Final MRP Old'])
amazon_sale_report_df = handle_missing_values(amazon_sale_report_df, ['Amount'])
may_2022_df = handle_missing_values(may_2022_df, ['Weight', 'TP', 'MRP Old', 'Final MRP Old'])

# Check missing values after handling
print("Sale Report Missing Values After Handling:")
print(sale_report_df.isnull().sum())

print("\nP & L March 2021 Missing Values After Handling:")
print(p_and_l_march_2021_df.isnull().sum())

print("\nAmazon Sale Report Missing Values After Handling:")
print(amazon_sale_report_df.isnull().sum())

print("\nMay 2022 Missing Values After Handling:")
print(may_2022_df.isnull().sum())

Sale Report Missing Values After Handling:
index          0
SKU Code      83
Design No.    36
Stock          0
Category      45
Size          36
Color         45
dtype: int64

P & L March 2021 Missing Values After Handling:
index              0
Sku                0
Style Id           0
Catalog           73
Category          73
Weight             0
TP 1               0
TP 2               0
MRP Old            0
Final MRP Old      0
Ajio MRP          37
Amazon MRP        37
Amazon FBA MRP    37
Flipkart MRP      37
Limeroad MRP      37
Myntra MRP        31
Paytm MRP         37
Snapdeal MRP      37
dtype: int64

Amazon Sale Report Missing Values After Handling:
index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                    0
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

May 2022 Missing Values After Handling:
index              0
Sku                0
Style Id           0
Catalog           73
Category          73
Weight             0
TP                 0
MRP Old            0
Final MRP Old      0
Ajio MRP          37
Amazon MRP        37
Amazon FBA MRP    37
Flipkart MRP      37
Limeroad MRP      37
Myntra MRP        31
Paytm MRP         37
Snapdeal MRP      37
dtype: int64

## Step 8: Detect and Handle Outliers

Outliers can skew the analysis and provide misleading results. By removing outliers, we ensure that the dataset represents typical values more accurately.

In [18]:
# Detect and handle outliers
def detect_handle_outliers(df):
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        df = df[(np.abs(df[col] - df[col].mean()) <= (3 * df[col].std())) | df[col].isnull()]
    return df

sale_report_df = detect_handle_outliers(sale_report_df)
p_and_l_march_2021_df = detect_handle_outliers(p_and_l_march_2021_df)
amazon_sale_report_df = detect_handle_outliers(amazon_sale_report_df)
may_2022_df = detect_handle_outliers(may_2022_df)

## Step 9: Data Consistency

Here we'll ensure that the 'Date' column in the amazon_sale_report_df DataFrame is consistently formatted as a datetime.

In [19]:
# Ensure consistency in categorical values and date formats
def ensure_consistency(df):
    # Example: Convert date columns to datetime format
    if 'Date' in df.columns:
        try:
            # Try to parse with a known format
            df['Date'] = pd.to_datetime(df['Date'], format='%m-%d-%y', errors='coerce')
        except ValueError:
            # Fallback to general parsing
            df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    return df

amazon_sale_report_df = ensure_consistency(amazon_sale_report_df)

# Display the first few rows to verify date parsing
print(amazon_sale_report_df.head())

   index             Order ID       Date                        Status  \
0      0  405-8078784-5731545 2022-04-30                     Cancelled
1      1  171-9198151-1101146 2022-04-30  Shipped - Delivered to Buyer
2      2  404-0687676-7273146 2022-04-30                       Shipped
3      3  403-9615377-8133951 2022-04-30                     Cancelled
4      4  407-1069790-7240320 2022-04-30                       Shipped

  Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0   Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1   Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2     Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3   Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4     Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL

        Category  ... currency  Amount    ship-city   ship-state  \
0            Set  ...      INR  647.62       MUMBAI  MAHARASHTRA
1          kurta  ...      INR  406.00    BENGALURU    KARNATAKA
2          kurta  ...      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3  Western Dress  ...      INR  753.33   PUDUCHERRY   PUDUCHERRY
4            Top  ...      INR  574.00      CHENNAI   TAMIL NADU

  ship-postal-code  ship-country  \
0         400081.0            IN
1         560085.0            IN
2         410210.0            IN
3         605008.0            IN
4         600073.0            IN

                                       promotion-ids    B2B  fulfilled-by  \
0                                                NaN  False     Easy Ship
1  Amazon PLCC Free-Financing Universal Merchant ...  False     Easy Ship
2       IN Core Free Shipping 2015/04/08 23-48-5-108   True           NaN
3                                                NaN  False     Easy Ship
4                                                NaN  False           NaN

  Unnamed: 22
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 24 columns]

## Step 10: Implementing Consistent Column Naming

Due to formatting inconsistency, we'll change column names to match the column names used in the create_table.sql script, preventing problems upon data import:
);

In [20]:
# Column mappings
sale_report_columns = {
    'SKU Code': 'sku_code',
    'Design No.': 'design_no',
    'Stock': 'stock',
    'Category': 'category',
    'Size': 'size',
    'Color': 'color'
}

p_and_l_march_2021_columns = {
    'Sku': 'sku',
    'Style Id': 'style_id',
    'Catalog': 'catalog',
    'Category': 'category',
    'Weight': 'weight',
    'TP 1': 'tp1',
    'TP 2': 'tp2',
    'MRP Old': 'mrp_old',
    'Final MRP Old': 'final_mrp_old',
    'Ajio MRP': 'ajio_mrp',
    'Amazon MRP': 'amazon_mrp',
    'Amazon FBA MRP': 'amazon_fba_mrp',
    'Flipkart MRP': 'flipkart_mrp',
    'Limeroad MRP': 'limeroad_mrp',
    'Myntra MRP': 'myntra_mrp',
    'Paytm MRP': 'paytm_mrp',
    'Snapdeal MRP': 'snapdeal_mrp'
}

amazon_sale_report_columns = {
    'Order ID': 'order_id',
    'Date': 'date',
    'Status': 'status',
    'Fulfilment': 'fulfillment',
    'Sales Channel ': 'sales_channel',
    'ship-service-level': 'ship_service_level',
    'Style': 'style',
    'SKU': 'sku',
    'Category': 'category',
    'Size': 'size',
    'ASIN': 'asin',
    'Courier Status': 'courier_status',
    'Qty': 'qty',
    'currency': 'currency',
    'Amount': 'amount',
    'ship-city': 'ship_city',
    'ship-state': 'ship_state',
    'ship-postal-code': 'ship_postal_code',
    'ship-country': 'ship_country',
    'promotion-ids': 'promotion_ids',
    'B2B': 'b2b',
    'fulfilled-by': 'fulfilled_by'
}

may_2022_columns = {
    'Sku': 'sku',
    'Style Id': 'style_id',
    'Catalog': 'catalog',
    'Category': 'category',
    'Weight': 'weight',
    'TP': 'tp',
    'MRP Old': 'mrp_old',
    'Final MRP Old': 'final_mrp_old',
    'Ajio MRP': 'ajio_mrp',
    'Amazon MRP': 'amazon_mrp',
    'Amazon FBA MRP': 'amazon_fba_mrp',
    'Flipkart MRP': 'flipkart_mrp',
    'Limeroad MRP': 'limeroad_mrp',
    'Myntra MRP': 'myntra_mrp',
    'Paytm MRP': 'paytm_mrp',
    'Snapdeal MRP': 'snapdeal_mrp'
}

## Step 11: Define Helper Functions for Data Cleaning and Manipulation

This cell includes functions that clean the data frame by removing unnecessary columns, standardizing column names, handling duplicates, and verifying SKUs.

In [21]:
# Function to remove the 'index' column if it exists
def remove_index_column(df):
    if 'index' in df.columns:
        df.drop(columns=['index'], inplace=True)
    return df

# Function to remove 'Unnamed' columns if they exist
def remove_unnamed_columns(df):
    unnamed_cols = [col for col in df.columns if col.lower().startswith('unnamed')]
    if unnamed_cols:
        df.drop(columns=unnamed_cols, inplace=True)
    return df

# Function to standardize column names
def standardize_column_names(df):
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_')
    return df

# Function to validate and add missing columns
def add_missing_columns(df, required_columns):
    for col in required_columns:
        if col not in df.columns:
            df[col] = np.nan
    return df

# Function to clean and rename columns
def clean_and_rename(df, column_mapping):
    df.rename(columns=column_mapping, inplace=True)
    return df

# Handle duplicates in primary key columns
def handle_duplicates(df, primary_key):
    if primary_key in df.columns:
        duplicates = df[df.duplicated(subset=[primary_key], keep=False)]
        if not duplicates.empty:
            print(f"Found duplicates in {primary_key} column:")
            print(duplicates)
            df = df.drop_duplicates(subset=[primary_key])
    else:
        print(f"{primary_key} column not found in DataFrame.")
    return df

# Ensure all SKUs in sale_report, p_and_l_march_2021, and may_2022 exist in amazon_products
def verify_and_add_skus(reference_df, target_df, key_column):
    missing_skus = target_df[~target_df[key_column].isin(reference_df['sku'])]
    if not missing_skus.empty:
        new_products = missing_skus[[key_column, 'style', 'category', 'size']].drop_duplicates()
        new_products['asin'] = ''  # Add ASIN if available or keep as empty
        reference_df = pd.concat([reference_df, new_products], ignore_index=True)
    return reference_df

## Step 12: Renaming, Standardizing, Column Removal, and Augmentation

In [22]:
# Apply cleaning and renaming to DataFrames
sale_report_df = clean_and_rename(sale_report_df, sale_report_columns)
p_and_l_march_2021_df = clean_and_rename(p_and_l_march_2021_df, p_and_l_march_2021_columns)
amazon_sale_report_df = clean_and_rename(amazon_sale_report_df, amazon_sale_report_columns)
may_2022_df = clean_and_rename(may_2022_df, may_2022_columns)

# Apply standardization and cleaning to DataFrames
sale_report_df = standardize_column_names(remove_unnamed_columns(remove_index_column(sale_report_df)))
p_and_l_march_2021_df = standardize_column_names(remove_unnamed_columns(remove_index_column(p_and_l_march_2021_df)))
amazon_sale_report_df = standardize_column_names(remove_unnamed_columns(remove_index_column(amazon_sale_report_df)))
may_2022_df = standardize_column_names(remove_unnamed_columns(remove_index_column(may_2022_df)))

# Required columns for amazon_products
required_product_columns = ['sku', 'style', 'category', 'size', 'asin']
sale_report_df = add_missing_columns(sale_report_df, required_product_columns)
p_and_l_march_2021_df = add_missing_columns(p_and_l_march_2021_df, required_product_columns)
may_2022_df = add_missing_columns(may_2022_df, required_product_columns)

## Step 13: Split Amazon Sale Report into Separate Dataframes

This is needed to properly organize information in the database while also ensuring data integrity. These are the following tables:

- amazon_orders_df: Contains order-specific information, ensuring that each order is unique by order_id.
- amazon_products_df: Contains product-specific information, ensuring each product is unique by sku.
- amazon_order_items_df: Contains detailed information about items in each order, linking orders and products.

In [23]:
# Function to split amazon_sale_report_df into orders, products, and order_items
def split_amazon_sale_report(amazon_sale_report_df):
    required_columns = ['order_id', 'date', 'status', 'fulfillment', 'sales_channel', 'ship_service_level', 'courier_status', 'currency', 'amount', 'ship_city', 'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids', 'b2b', 'fulfilled_by', 'sku', 'style', 'category', 'size', 'asin', 'qty']
    amazon_sale_report_df = add_missing_columns(amazon_sale_report_df, required_columns)

    amazon_orders_df = amazon_sale_report_df.drop_duplicates(subset=['order_id']).copy()
    amazon_orders_df = amazon_orders_df[['order_id', 'date', 'status', 'fulfillment', 'sales_channel', 'ship_service_level', 'courier_status', 'currency', 'amount', 'ship_city', 'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids', 'b2b', 'fulfilled_by']]
    
    amazon_products_df = amazon_sale_report_df.drop_duplicates(subset=['sku']).copy()
    amazon_products_df = amazon_products_df[['sku', 'style', 'category', 'size', 'asin']]
    
    amazon_order_items_df = amazon_sale_report_df[['order_id', 'sku', 'style', 'category', 'size', 'asin', 'qty', 'amount']]
    
    return amazon_orders_df, amazon_products_df, amazon_order_items_df

# Split amazon_sale_report_df into orders, products, and order_items
amazon_orders_df, amazon_products_df, amazon_order_items_df = split_amazon_sale_report(amazon_sale_report_df)

## Step 14: Handle Duplicates

In [31]:
# Apply the removal functions
sale_report_df = handle_duplicates(remove_unnamed_columns(remove_index_column(sale_report_df)), 'sku_code')
p_and_l_march_2021_df = handle_duplicates(remove_unnamed_columns(remove_index_column(p_and_l_march_2021_df)), 'sku')
amazon_sale_report_df = handle_duplicates(remove_unnamed_columns(remove_index_column(amazon_sale_report_df)), 'order_id')
may_2022_df = handle_duplicates(remove_unnamed_columns(remove_index_column(may_2022_df)), 'sku')

## Step 15: Verify and Add Missing SKUs

This cell verifies that all SKUs are present and adds any missing SKUs to the Amazon products DataFrame.

In [32]:
# Add missing SKUs to amazon_products_df
amazon_products_df = verify_and_add_skus(amazon_products_df, sale_report_df, 'sku_code')
amazon_products_df = verify_and_add_skus(amazon_products_df, p_and_l_march_2021_df, 'sku')
amazon_products_df = verify_and_add_skus(amazon_products_df, amazon_order_items_df, 'sku')
amazon_products_df = verify_and_add_skus(amazon_products_df, may_2022_df, 'sku')

## Step 16: Final Cleaning

Final clean-up by removing rows with null SKUs and ensuring that there are no duplicates in the order items data frame.

In [33]:
# Remove rows with null SKU in amazon_products_df
amazon_products_df = amazon_products_df.dropna(subset=['sku'])

# Ensure no duplicates in amazon_order_items
amazon_order_items_df = amazon_order_items_df.drop_duplicates(subset=['order_id', 'sku'])

print("\nUpdated amazon_products with missing SKUs.")

Updated amazon_products with missing SKUs.

## Step 17: Handling and Updating Missing SKUs

Ensures that all SKUs from sales reports and other data sources are included in the amazon_products list, which is crucial for accurate inventory and sales analysis.

In [34]:
# Identify missing SKUs from each table
missing_skus = pd.Series(dtype='object')

for df in [sale_report_df, p_and_l_march_2021_df, may_2022_df]:
    if 'sku_code' in df.columns:
        missing_skus = pd.concat([missing_skus, df[~df['sku_code'].isin(amazon_products_df['sku']) & df['sku_code'].notna()]['sku_code']])
    elif 'sku' in df.columns:
        missing_skus = pd.concat([missing_skus, df[~df['sku'].isin(amazon_products_df['sku']) & df['sku'].notna()]['sku']])

missing_skus = missing_skus.drop_duplicates()

# Add missing SKUs to amazon_products
if len(missing_skus) > 0:
    new_products = pd.DataFrame({
        'sku': missing_skus,
        'style': 'Unknown',
        'category': 'Unknown',
        'size': 'Unknown',
        'asin': 'Unknown'
    })
    amazon_products_df = pd.concat([amazon_products_df, new_products], ignore_index=True)
    amazon_products_df.to_csv('C:/Users/matth/ecommerce_mba_project/data/cleaned/amazon_products_cleaned.csv', index=False)
    print("Added missing SKUs to amazon_products.")
else:
    print("No missing SKUs found.")

No missing SKUs found.

## Step 18: Log Issues

This is to identify and log rows with missing values in each data frame for further inspection and potential correction.

In [35]:
# Log problematic rows
def log_problematic_rows(df, key):
    problematic_rows = df[df.isnull().any(axis=1)]
    if not problematic_rows.empty:
        log_file = os.path.join(log_path, f'{key}_log.csv')
        problematic_rows.to_csv(log_file, index=False)
        print(f"\nLogged problematic rows for {key} to {log_file}")

log_problematic_rows(sale_report_df, 'sale_report')
log_problematic_rows(p_and_l_march_2021_df, 'p_and_l_march_2021')
log_problematic_rows(amazon_sale_report_df, 'amazon_sale_report')
log_problematic_rows(may_2022_df, 'may_2022')

Logged problematic rows for sale_report to C:/Users/matth/ecommerce_mba_project/data/logs\sale_report_log.csv

Logged problematic rows for p_and_l_march_2021 to C:/Users/matth/ecommerce_mba_project/data/logs\p_and_l_march_2021_log.csv

Logged problematic rows for amazon_sale_report to C:/Users/matth/ecommerce_mba_project/data/logs\amazon_sale_report_log.csv

Logged problematic rows for may_2022 to C:/Users/matth/ecommerce_mba_project/data/logs\may_2022_log.csv

## Step 19: Save Cleaned Data

In [36]:

# Save cleaned data to new CSV files
def save_cleaned_data(df, key):
    new_path = os.path.join(cleaned_path, key + '_cleaned.csv')
    df.to_csv(new_path, index=False)
    print(f"\nSaved cleaned data to {new_path}")

save_cleaned_data(amazon_orders_df, 'amazon_orders')
save_cleaned_data(amazon_products_df, 'amazon_products')
save_cleaned_data(amazon_order_items_df, 'amazon_order_items')
save_cleaned_data(sale_report_df, 'sale_report')
save_cleaned_data(p_and_l_march_2021_df, 'p_and_l_march_2021')
save_cleaned_data(may_2022_df, 'may_2022')

Saved cleaned data to C:/Users/matth/ecommerce_mba_project/data/cleaned\amazon_orders_cleaned.csv

Saved cleaned data to C:/Users/matth/ecommerce_mba_project/data/cleaned\amazon_products_cleaned.csv

Saved cleaned data to C:/Users/matth/ecommerce_mba_project/data/cleaned\amazon_order_items_cleaned.csv

Saved cleaned data to C:/Users/matth/ecommerce_mba_project/data/cleaned\sale_report_cleaned.csv

Saved cleaned data to C:/Users/matth/ecommerce_mba_project/data/cleaned\p_and_l_march_2021_cleaned.csv

Saved cleaned data to C:/Users/matth/ecommerce_mba_project/data/cleaned\may_2022_cleaned.csv

## Step 20: Processing and Saving Cleaned CSV Files

This will maintain consistent column names and formats across all CSV files, which is crucial for downstream data processing and analysis.

In [37]:
# List of CSV files and their expected columns
csv_files = {
    'amazon_orders_cleaned.csv': ['order_id', 'date', 'status', 'fulfillment', 'sales_channel', 'ship_service_level', 'courier_status', 'currency', 'amount', 'ship_city', 'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids', 'b2b', 'fulfilled_by'],
    'amazon_products_cleaned.csv': ['sku', 'style', 'category', 'size', 'asin'],
    'amazon_order_items_cleaned.csv': ['order_id', 'sku', 'style', 'category', 'size', 'asin', 'qty', 'amount'],
    'sale_report_cleaned.csv': ['sku_code', 'design_no', 'stock', 'category', 'size', 'color'],
    'p_and_l_march_2021_cleaned.csv': ['sku', 'style_id', 'catalog', 'category', 'weight', 'tp1', 'tp2', 'mrp_old', 'final_mrp_old', 'ajio_mrp', 'amazon_mrp', 'amazon_fba_mrp', 'flipkart_mrp', 'limeroad_mrp', 'myntra_mrp', 'paytm_mrp', 'snapdeal_mrp'],
    'may_2022_cleaned.csv': ['sku', 'style_id', 'catalog', 'category', 'weight', 'tp', 'mrp_old', 'final_mrp_old', 'ajio_mrp', 'amazon_mrp', 'amazon_fba_mrp', 'flipkart_mrp', 'limeroad_mrp', 'myntra_mrp', 'paytm_mrp', 'snapdeal_mrp']
}

base_path = 'C:/Users/matth/ecommerce_mba_project/data/cleaned/'

for file_name, columns in csv_files.items():
    file_path = base_path + file_name
    try:
        df = pd.read_csv(file_path, usecols=columns)
        df.to_csv(file_path, index=False)
        print(f"Cleaned and saved {file_name}")
    except Exception as e:
        print(f"Error processing {file_name}: {e}")

Cleaned and saved amazon_orders_cleaned.csv
Cleaned and saved amazon_products_cleaned.csv
Cleaned and saved amazon_order_items_cleaned.csv
Cleaned and saved sale_report_cleaned.csv
Cleaned and saved p_and_l_march_2021_cleaned.csv
Cleaned and saved may_2022_cleaned.csv